backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/img"
public: "static/img"

collections:
  # Info in /posts/
  - name: "info" # Used in routes, e.g., /admin/collections/blog
    label: "Info" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal terbit", name: "date", widget: "datetime" }
      - { label: "Kutipan", name: "excerpt", widget: "text" }
      - { label: "Label", name: "tags", widget: "list", default: ["post"] }
      - { label: "Konten", name: "body", widget: "markdown" }
  # Pages in /pages/
  - name: "pages"
    label: "Laman"
    folder: "src/pages"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal terbit", name: "date", widget: "datetime" }
      - { label: "Kutipan", name: "excerpt", widget: "text" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  # Fundraises in /fundraises/
  - name: "fundraises"
    label: "Penggalangan Dana"
    folder: "src/fundraises"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal terbit", name: "date", widget: "datetime" }
      - { label: "Kutipan", name: "excerpt", widget: "text" }
      - label: "Penggalangan Dana"
        name: "fra"
        widget: "object"
        fields:
          - { label: "Target ditentukan", name: "hasTarget", widget: "boolean", default: true }
          - { label: "Target", name: "target", widget: "number", default: "5000000" }
          - { label: "Terkumpul", name: "raised", widget: "number", default: "2000000"}
      - label: "Spanduk"
        name: "banner"
        widget: "object"
        fields :
          - { label: "Gambar", name: "image", widget: "image", allow_multiple: "false" }
          - { label: "Gaya", name: "style", widget: "select", options: [ "contain", "cover" ], default: "contain" }
      - { label: "Label", name: "tags", widget: "list", default: ["fundraise"] }
